// v2.go/frontend/javascript/login.jsx
// εncooη : data structuration, presentation and navigation.
// Copyright David Lambert 2022

class Login extends React.Component {
	constructor(props) {
		super(props)
		this.dbNameInput = null
		this.setDbNameRef = element => { this.dbNameInput = element }
		this.idInput = null
		this.setIdRef = element => { this.idInput = element }
		this.passwordInput = null
		this.setPasswordRef = element => { this.passwordInput = element }
	}

	authenticate() {
		const updatedDbName = this.props.dbName != '' ? this.props.dbName : this.dbNameInput.value
		if(updatedDbName == '') {
			alert("Database name is required.")
			return null
		}
		if(this.idInput.value == '' || this.passwordInput.value == '') {
			alert("Username and passphrase are both required.")
			return null
		}
		fetch(`/${updatedDbName}/api/v1/authentication`, {
			method: 'POST',
			headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
			body: JSON.stringify({ id: this.idInput.value, password: btoa(this.passwordInput.value) })
		})
		.then(response => {
			if(response.status == 400) {
				alert("Incorrect user credentials.")
				return null
			}
			if(response.status != 200) {
				alert(`Problem ${response.status} is reported.`)
				return null
			}
			return response.json() 
		})
		.then(responseJson => {
			if (responseJson != null) {
				localStorage.setItem(`access_token_${updatedDbName}`, responseJson.token)
			}
			if(this.props.dbName == '') location.href = `/${updatedDbName}/`
			else location.reload()
		})
	}

	render() {
		return (
			<div className="container">
				<div className="row">
					<div className="col"></div>
					<div className="col">
						<br/><br/><br/><br/><br/><br/><br/>
						<center>
							<h1>{this.props.appName}</h1>
							<small className="text-muted">{this.props.appTag}</small>
							<br/>
							<br/>
							{this.props.dbName != "" && <h3>{this.props.dbName}</h3>}
						</center>
						{this.props.dbName == "" &&
							<div className="mb-3">
								<label htmlFor="dbName" className="form-label">Database</label>
								<input type="text" 
									className="form-control" 
									id="dbName" 
									ref={this.setDbNameRef}/>
							</div>
						}
						<div className="mb-3">
							<label htmlFor="id" className="form-label">Username</label>
							<input type="text" 
								className="form-control" 
								id="id" 
								ref={this.setIdRef}
								aria-describedby="idHelp"/>
							<div id="idHelp" className="form-text">We'll never share your data with anyone else.</div>
						</div>
						<div className="mb-3">
							<label htmlFor="password" className="form-label">Passphrase</label>
							<input type="password" 
								className="form-control" 
								id="password"
								ref={this.setPasswordRef}/>
							<div id="passwordHelp" className="form-text">
								A passphrase is a sequence of words or other text used to control access 
								to a computer system, program or data. 
								It is similar to a password in usage, but a passphrase is generally longer 
								for added security.
							</div>
						</div>
						<div className="d-grid gap-2">
							<button type="button" 
								className="btn btn-outline-primary"
								onClick={() => this.authenticate()}>
								Log in {this.props.dbName} <i className="bi bi-box-arrow-in-right"></i>
							</button>
						</div>
					</div>
					<div className="col"></div>
				</div>
			</div>
		)
	}
}

// frontend/src/routes/[[dbName]]/[[gridUuid]]/Login.svelte
<script  lang="ts">
  import { Button } from 'flowbite-svelte'
  let { context } = $props()
  let loginId = $state("")
  let loginPassword = $state("")
</script>

<div class="flex flex-col items-center justify-center mx-auto mt-32 md:h-fit lg:py-0">
  <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
      <form class="space-y-4 md:space-y-6" action="#">
        <h1 class="text-center mb-2 text-4xl font-extrabold text-gray-900 dark:text-white">
          εncooη: {context.dbName}
        </h1>
        <div>
          <label for="login" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
          <input type="text" id="login" 
                  class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-gray-600 focus:border-gray-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                  placeholder="username" required={true}
                  bind:value={loginId}>
          <div class="mt-2 font-thin text-xs">We'll never share your data with anyone else.</div>
        </div>
        <div>
          <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Passphrase</label>
          <input type="password" id="password" placeholder="••••••••" 
                  class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-gray-600 focus:border-gray-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                  required={true}
                  bind:value={loginPassword}>
          <div class="mt-2 font-thin text-xs">
            A passphrase is a sequence of words or other text used to control access 
            to a computer system, program or data. 
            It is similar to a password in usage, but a passphrase is generally longer 
            for added security.
          </div>
        </div>
        <Button type="submit" color="blue" size="md" class="w-full" onclick={() => context.authentication(loginId, loginPassword)}>
            Sign in
        </Button>
      </form>
    </div>
  </div>
</div>
